name: siklo

services:
  postgres:
    image: postgres:16-alpine
    container_name: siklo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: siklo
      POSTGRES_PASSWORD: softwaredev
      POSTGRES_DB: siklo_dev
    ports:
      - "5433:5432"
    volumes:
      - siklo_pgdata:/var/lib/postgresql/data

volumes:
  siklo_pgdata: