import { FeatureItem } from "../types/features.types";

export const defaultFeatures: FeatureItem[] = [
  {
    id: "rotation",
    title: "Automated Turn Scheduling",
    subtitle: "Smart Payout Engine",
    description: "Systematically computes payout orders, tracks contribution cycles, and manages turn dates automatically without manual spreadsheet calculations.",
    iconName: "RotateCcw",
    category: "rotation",
    highlightBadge: "Core Feature",
  },
  {
    id: "ledger",
    title: "Shared Transparent Ledger",
    subtitle: "Unalterable Audit Trail",
    description: "Real-time contribution logging gives all group members instant visibility into payments, turns, and total lump-sum payout funds.",
    iconName: "BookOpen",
    category: "transparency",
    highlightBadge: "100% Transparent",
  },
  {
    id: "proof",
    title: "Digital Payment Verification",
    subtitle: "Digital Proof Logs",
    description: "Upload payment screenshots or transaction reference IDs so group admins and members can verify contributions instantly with timestamped proof.",
    iconName: "FileCheck",
    category: "transparency",
    highlightBadge: "Verification",
  },
  {
    id: "groups",
    title: "Group & Invite Management",
    subtitle: "Secure Join System",
    description: "Easily set up Paluwagan groups, set flexible payment schedules (Daily, Weekly, Every 2 Weeks, Monthly, Quarterly), and invite trusted members using simple invite codes.",
    iconName: "Users",
    category: "collaboration",
  },
  {
    id: "activity-logs",
    title: "Real-Time Activity Logs",
    subtitle: "Shared Audit Feed",
    description: "Track all member payment confirmations, payout turn advancements, and group status updates in a real-time activity audit feed.",
    iconName: "History",
    category: "collaboration",
  },
  {
    id: "sequence",
    title: "Flexible Turn Sequence",
    subtitle: "Turn Order Choices",
    description: "Choose how members get paid: first-come first-served queue, randomized lucky draw lots, or letting members choose their preferred turn date.",
    iconName: "Shuffle",
    category: "rotation",
  },
  {
    id: "reminders",
    title: "Automated Payment Alerts",
    subtitle: "Smart Notifications",
    description: "Never miss a contribution deadline with automatic in-app alerts and turn updates before your cycle payment is due.",
    iconName: "BellRing",
    category: "collaboration",
  },
  {
    id: "dashboard",
    title: "Interactive Savings Dashboard",
    subtitle: "Live Progress Monitor",
    description: "Track expected payout dates, total savings pool, active paluwagan cycles, and group milestone progress at a glance.",
    iconName: "LayoutDashboard",
    category: "rotation",
  },
  {
    id: "wallets",
    title: "Mobile Wallet Friendly",
    subtitle: "E-Wallet Support",
    description: "Built for Philippine savings culture with support for mobile wallet payment logging, transaction receipts, and contribution proof.",
    iconName: "Wallet",
    category: "transparency",
  },
  {
    id: "exports",
    title: "Exportable Cycle Reports",
    subtitle: "Downloadable Statements",
    description: "Download a clean, printable summary of all payments and turn payouts for your personal records or group review.",
    iconName: "FileText",
    category: "transparency",
    highlightBadge: "Coming Soon",
  },
  {
    id: "security",
    title: "Account & Profile Security",
    subtitle: "Protected Credentials",
    description: "Manage personal profile data, update passwords safely, and maintain strict data privacy while participating in savings groups.",
    iconName: "ShieldCheck",
    category: "customization",
  },
  {
    id: "theme",
    title: "Dark & Light Mode Support",
    subtitle: "Dynamic Personalization",
    description: "Seamlessly switch between dark mode and light mode aesthetics with responsive glassmorphism designs tailored for any screen size.",
    iconName: "SunMoon",
    category: "customization",
  },
];
