import { FeatureItem } from "../types/features.types";

export const defaultFeatures: FeatureItem[] = [
  {
    id: "rotation",
    title: "Automated Turn Scheduling",
    subtitle: "Smart Payout Engine",
    description: "Systematically computes payout orders, tracks contribution cycles, and manages turn dates automatically without manual spreadsheet calculations.",
    iconName: "RotateCcw",
    category: "rotation",
    highlightBadge: "Core Feature",
  },
  {
    id: "ledger",
    title: "Shared Transparent Ledger",
    subtitle: "Unalterable Audit Trail",
    description: "Real-time contribution logging gives all group members instant visibility into payments, turns, and total lump-sum payout funds.",
    iconName: "BookOpen",
    category: "transparency",
    highlightBadge: "100% Transparent",
  },
  {
    id: "proof",
    title: "Digital Payment Verification",
    subtitle: "Digital Proof Logs",
    description: "Upload payment screenshots or transaction reference IDs so group admins and members can verify contributions instantly with timestamped proof.",
    iconName: "FileCheck",
    category: "transparency",
    highlightBadge: "Verification",
  },
  {
    id: "groups",
    title: "Group & Invite Management",
    subtitle: "Secure Join System",
    description: "Easily set up Paluwagan groups, customize billing cycles (Weekly, Bi-Weekly, Monthly), and invite trusted members using secure 6-digit invite codes.",
    iconName: "Users",
    category: "collaboration",
  },
  {
    id: "chat",
    title: "Real-Time Group Chat",
    subtitle: "In-App Communication",
    description: "Stay connected with fellow members directly inside each group. Send announcements, discuss contribution dates, and confirm payouts instantly.",
    iconName: "MessageSquare",
    category: "collaboration",
  },
  {
    id: "sequence",
    title: "Custom Turn Sequence",
    subtitle: "Flexible Payout Draw",
    description: "Choose fixed, random draw, or consensus sequence payout turns tailored to your savings group's agreed rules.",
    iconName: "Shuffle",
    category: "rotation",
  },
  {
    id: "reminders",
    title: "Automated Payment Alerts",
    subtitle: "Smart Notifications",
    description: "Never miss a contribution deadline with automatic in-app alerts and turn updates before your cycle payment is due.",
    iconName: "BellRing",
    category: "collaboration",
  },
  {
    id: "dashboard",
    title: "Interactive Savings Dashboard",
    subtitle: "Live Progress Monitor",
    description: "Track expected payout dates, total savings pool, active paluwagan cycles, and group milestone progress at a glance.",
    iconName: "LayoutDashboard",
    category: "rotation",
  },
  {
    id: "wallets",
    title: "Mobile Wallet Friendly",
    subtitle: "E-Wallet Support",
    description: "Built for Philippine savings culture with support for mobile wallet payment logging, transaction receipts, and contribution proof.",
    iconName: "Wallet",
    category: "transparency",
  },
  {
    id: "exports",
    title: "Exportable Cycle Reports",
    subtitle: "Downloadable Statements",
    description: "Generate clean cycle summaries and contribution audit logs for personal records or group financial verification.",
    iconName: "FileText",
    category: "transparency",
  },
  {
    id: "security",
    title: "Account & Profile Security",
    subtitle: "Protected Credentials",
    description: "Manage personal profile data, update passwords safely, and maintain strict data privacy while participating in savings groups.",
    iconName: "ShieldCheck",
    category: "customization",
  },
  {
    id: "theme",
    title: "Dark & Light Mode Support",
    subtitle: "Dynamic Personalization",
    description: "Seamlessly switch between dark mode and light mode aesthetics with responsive glassmorphism designs tailored for any screen size.",
    iconName: "SunMoon",
    category: "customization",
  },
];
